# Generated by Django 5.1.7 on 2025-07-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrprofile",
            name="company_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="hrprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hrprofile",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hrprofile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="hrprofile",
            name="linkedin_profile",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hrprofile",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
