# Generated by Django 5.1.7 on 2025-07-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_alter_hrprofile_company_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrprofile",
            name="company_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
