# Generated by Django 5.2.5 on 2025-08-12 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_pushsubscription_endpoint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pushsubscription",
            unique_together={("user", "endpoint")},
        ),
    ]
