# Generated by Django 5.2.5 on 2025-08-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_pushsubscription_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pushsubscription",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="endpoint",
            field=models.TextField(unique=True),
        ),
    ]
