# Generated by Django 5.1.7 on 2025-07-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                    ("Not prefer to say", "Prefer not to say"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
