# Generated by Django 5.1.7 on 2025-07-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_picture",
        ),
    ]
