# Generated by Django 5.1.7 on 2025-07-28 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job_applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleInterviewsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interview_link", models.URLField()),
                ("scheduled_time", models.DateTimeField()),
                ("is_completed", models.BooleanField(default=False)),
                ("ai_feedback", models.TextField(blank=True, null=True)),
                ("ai_score", models.FloatField(blank=True, null=True)),
                (
                    "job_applications",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview",
                        to="job_applications.jobapplications",
                    ),
                ),
            ],
        ),
    ]
