# Generated by Django 5.2.5 on 2025-08-18 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview_test", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="A short, URL-friendly version of the name.",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RemoveField(
            model_name="question",
            name="correct_options",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_type",
        ),
        migrations.AddField(
            model_name="question",
            name="correct_option",
            field=models.CharField(
                blank=True,
                help_text="For aptitude questions, the correct character (e.g., 'A', 'B'). Can be blank for coding questions.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='For aptitude: [{"char": "A", "text": "Option A"}]. For coding: can be empty or have starter code.',
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(
                help_text="The main text of the question or coding problem."
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="time_limit_seconds",
            field=models.IntegerField(
                default=90,
                help_text="Time allowed for this specific question in seconds.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="interview_test.category",
            ),
        ),
    ]
