# Generated by Django 5.1.7 on 2025-07-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="end_date",
            new_name="application_deadline",
        ),
        migrations.RemoveField(
            model_name="job",
            name="domain",
        ),
        migrations.AddField(
            model_name="job",
            name="about_company",
            field=models.TextField(
                default="Information about the company is not provided."
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="assessment_questions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="company_name",
            field=models.CharField(default="Company Name", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="company_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="cover_letter_question",
            field=models.TextField(default="Why should you be hired for this role?"),
        ),
        migrations.AddField(
            model_name="job",
            name="degrees_or_streams",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="duration",
            field=models.CharField(default="3 months", max_length=50),
        ),
        migrations.AddField(
            model_name="job",
            name="experience_level",
            field=models.CharField(default="0-1 years", max_length=50),
        ),
        migrations.AddField(
            model_name="job",
            name="graduation_years",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("in_office", "In-office"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                default="remote",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(default="Work from Home", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="openings",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="perks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="ppo_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="require_resume",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="responsibilities",
            field=models.TextField(default="Responsibilities not provided."),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_or_stipend",
            field=models.CharField(default="Unpaid", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="time_commitment",
            field=models.CharField(
                choices=[("full_time", "Full-time"), ("part_time", "Part-time")],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="who_can_apply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="women_reentry",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(default="Job description not provided."),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills_required",
            field=models.TextField(default="Not specified"),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(default="Job Title", max_length=255),
        ),
    ]
