# Generated by Django 5.1.7 on 2025-07-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_rename_end_date_job_application_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="ppo_available",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
