# Generated by Django 5.1.7 on 2025-07-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_ppo_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="openings",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
