# Generated by Django 5.1.7 on 2025-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_studentprofile_mobile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
