# Generated by Django 5.1.7 on 2025-07-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_studentprofile_mobile_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="internship",
            old_name="stipened",
            new_name="stipend",
        ),
        migrations.RenameField(
            model_name="studentprofile",
            old_name="Interview_Feedback",
            new_name="interview_Feedback",
        ),
    ]
