# Generated by Django 5.1.7 on 2025-07-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_rename_stipened_internship_stipend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
