export const TEST_IDS = {
  signup: {
    usernameInput: "signup-username-input",
    firstNameInput: "signup-first-name-input",
    lastNameInput: "signup-last-name-input",
    emailInput: "signup-email-input",
    genderSelect: "signup-gender-select",
    roleSelect: "signup-role-select",
    passwordInput: "signup-password-input",
    confirmPasswordInput: "signup-confirm-password-input",
    createAccountButton: "signup-create-account-button",
    loginLink: "signup-login-link",
    form: "signup-form",
    title: "signup-title",
  },
  login: {
    emailInput: "login-email-input",
    passwordInput: "login-password-input",
    togglePasswordVisibilityButton: "login-toggle-password-visibility-button",
    submitButton: "login-submit-button",
    signupLink: "login-signup-link",
    forgotPasswordLink: "login-forgot-password-link",
    form: "login-form",
    title: "login-title",
    logoVideo: "login-logo-video",
    emailError: "login-email-error",
    passwordError: "login-password-error",
  },
};
